name: SesamCommunity CI&CD

on: 
  pull_request:
  push:
    paths-ignore: 
      - '**.md'
      - '**.rst'
    branches:
      - '**'
    tags-ignore: 
      - '**'
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Docker Login
        if: ${{ startsWith( github.ref, 'refs/tags/' ) || startsWith( github.ref, 'refs/heads/master' ) }}
        uses: docker/login-action@v1.8.0
        with:          
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
              
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: debug
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
          GITHUB_EVENTNAME: ${{ github.event_name }}
          GITHUB_EVENTPATH: ${{ github.event_path }}          
        run: |
          echo $GITHUB_EVENT
          echo $GITHUB_EVENTNAME
          echo $GITHUB_EVENTPATH
        shell: bash

      - name: dockerbuild, dockerpublish
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          # DOCKER_REPO_NAME: uncomment_and_set_to_docker_repo_name 
        run: bash <(curl -s https://raw.githubusercontent.com/meyhane/guidelines/meyhane-patch-1/git_action.sh)
        shell: bash
