name: SesamCommunity CI&CD

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        env:
          GITHUB: ${{ toJSON(github) }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          DOCKER_USERNAME: ${{ github.owner }}
          DOCKER_PASSWORD: ${{ secrets.SuperSecret }}
        run: |
          ls 
          echo "---"
          ls ../
          echo "---"
          ls ../../
          echo "---"
          ls ../../../
        shell: bash
