name: SesamCommunity CI&CD

on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run a one-line script
      env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          DOCKER_REPO_NAME: ''
      run: |
          bash <(curl -s https://raw.githubusercontent.com/meyhane/guidelines/git-actions/after_success.sh)
          cat /home/runner/.docker/config.json
      shell: bash
